title: My try blog 
author: Anugraha Paul
email: your-email@domain.com
description: Hi everyone ..so glad you are here !!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme: minimia 
show_excerpts: true # set to false to remove excerpts on the homepage
